@Dia5.API_HostAddress = http://localhost:5020

### 1. Obter Previsão do Tempo (Teste Inicial)
GET {{Dia5.API_HostAddress}}/weatherforecast/
Accept: application/json

###

### 2. Cadastrar Novo Usuário (Register)
POST {{Dia5.API_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "nome": "Usuario Teste",
  "email": "africanagrande@email.com",
  "senha": "SenhaForte123!"
}

###

### 3. Fazer Login
POST {{Dia5.API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "teste@email.com",
  "senha": "SenhaForte123!"
}
