// <auto-generated />
using System;
using Dia5.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dia5.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611213406_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dia5.Domain.Entities.Amizade", b =>
                {
                    b.Property<Guid>("UsuarioId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId2")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UsuarioId1", "UsuarioId2");

                    b.HasIndex("UsuarioId2");

                    b.ToTable("Amizades");
                });

            modelBuilder.Entity("Dia5.Domain.Entities.Despesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PagadorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("PagadorId");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("Dia5.Domain.Entities.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoConvite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CodigoConvite")
                        .IsUnique();

                    b.HasIndex("CriadoPorId");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Dia5.Domain.Entities.MembroGrupo", b =>
                {
                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GrupoId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MembrosGrupo");
                });

            modelBuilder.Entity("Dia5.Domain.Entities.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GrupoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PagadorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecebedorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("PagadorId");

                    b.HasIndex("RecebedorId");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("Dia5.Domain.Entities.ParticipanteDespesa", b =>
                {
                    b.Property<Guid>("DespesaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorDevido")
                        .HasColumnType("numeric");

                    b.HasKey("DespesaId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ParticipantesDespesa");
                });

            modelBuilder.Entity("Dia5.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoPerfil")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CriadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPerfil")
                        .IsUnique();

                    b.HasIndex("CriadoPorId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Dia5.Domain.Entities.Amizade", b =>
                {
                    b.HasOne("Dia5.Domain.Entities.Usuario", "Usuario1")
                        .WithMany("AmizadesIniciadas")
                        .HasForeignKey("UsuarioId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dia5.Domain.Entities.Usuario", "Usuario2")
                        .WithMany("AmizadesRecebidas")
                        .HasForeignKey("UsuarioId2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario1");

                    b.Navigation("Usuario2");
                });

            modelBuilder.Entity("Dia5.Domain.Entities.Despesa", b =>
                {
                    b.HasOne("Dia5.Domain.Entities.Grupo", "Grupo")
                        .WithMany("Despesas")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dia5.Domain.Entities.Usuario", "Pagador")
                        .WithMany("DespesasPagas")
                        .HasForeignKey("PagadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Pagador");
                });

            modelBuilder.Entity("Dia5.Domain.Entities.Grupo", b =>
                {
                    b.HasOne("Dia5.Domain.Entities.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriadoPor");
                });

            modelBuilder.Entity("Dia5.Domain.Entities.MembroGrupo", b =>
                {
                    b.HasOne("Dia5.Domain.Entities.Grupo", "Grupo")
                        .WithMany("Membros")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dia5.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Grupos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Dia5.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("Dia5.Domain.Entities.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId");

                    b.HasOne("Dia5.Domain.Entities.Usuario", "Pagador")
                        .WithMany()
                        .HasForeignKey("PagadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dia5.Domain.Entities.Usuario", "Recebedor")
                        .WithMany()
                        .HasForeignKey("RecebedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Pagador");

                    b.Navigation("Recebedor");
                });

            modelBuilder.Entity("Dia5.Domain.Entities.ParticipanteDespesa", b =>
                {
                    b.HasOne("Dia5.Domain.Entities.Despesa", "Despesa")
                        .WithMany("Participantes")
                        .HasForeignKey("DespesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dia5.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ParticipacoesDespesa")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Despesa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Dia5.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Dia5.Domain.Entities.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CriadoPor");
                });

            modelBuilder.Entity("Dia5.Domain.Entities.Despesa", b =>
                {
                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("Dia5.Domain.Entities.Grupo", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Membros");
                });

            modelBuilder.Entity("Dia5.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("AmizadesIniciadas");

                    b.Navigation("AmizadesRecebidas");

                    b.Navigation("DespesasPagas");

                    b.Navigation("Grupos");

                    b.Navigation("ParticipacoesDespesa");
                });
#pragma warning restore 612, 618
        }
    }
}
